### ISSUE TITLE
Make four image upload options using Tkinter

### ISSUE THREAD

**Issue by thevoxium** [thevoxium/BCD-Desktop#1]
The goal is to make a GUI window using Tkinter to get four images as input to the classifier.

1. It should have four separate buttons to open a file browser to get an image of each view as an input.
2. The widgets should be able to change size accordingly to the frame.

-Please follow the industry-grade coding style. The code should be readable to a newbie too.
- The code should be commented and it should have docstrings for each function.
- For reference please refer to the official Tkinter docs/tutorials. 
- Use function as much as you can. 

refer to these below if you need a starting point:

- [G4G](https://www.geeksforgeeks.org/file-explorer-in-python-using-tkinter/)
- [Stackoverflow](https://stackoverflow.com/questions/16798937/creating-a-browse-button-with-tkinter)

**Comment by BugBear646** [comment]
The goal to make a GUI window using Tkinter to get four images as input to the classifier is finally done. 😍 

It has one button with advanced options to open a file browser to get an image of each view as an input consecutively 4 times.
The widgets are able to change size accordingly to the frame.😎
